target("Engine")
    set_kind("static")
    add_deps("Log")
    add_packages("glm")
    add_files("*/*.cpp")
    add_headerfiles("**/**.h")
    add_includedirs("include",{public = true})
    set_group("engine")